let admin = [
    {
        id: "admin1",
        name: "Franco",
        lastName: "Rodriguez",
        age:" 25",
        email: "fran.rodriguez@gmail.com",
        password: "Fran2020",
        code: "ax20mt99ss21",
        verified: "true",
        logged: "true",
    },
    {
        id: "admin2",
        name: "Ignacio",
        lastName: "Gonzalez",
        age:"22",
        email: "IgnaGonzalez@hotmail.com",
        password: "Caramelo17",
        code: "gg19fr10aqxc",
        verified: "true",
        logged: "true",
    },
    {
        id: "admin3",
        name: "Diego",
        lastName: "Ramirez",
        age:"30",
        email: "dieguito_ramirez@gmail.com",
        password: "DG2021",
        code: "xx10cv12s887",
        verified: "true",
        logged: "true",
    },
    {
        id: "admin4",
        name: "Mauro",
        lastName: "Rosas",
        age:"22",
        email: "MauR@gmail.com",
        password: "Arboleda10*",
        code: "b102hy2312mm",
        verified: "true",
        logged: "true",
    }
]